POST http://localhost/api/authors HTTP/1.1
Content-Type: application/json


{
    "surname": "Пушкин",
    "name": "Александр",
    "patronymic": "Сергеевич",
    "biography": "Русский поэт, драматург и прозаик, заложивший основы русского реалистического направления, литературный критик и теоретик литературы, историк, публицист, журналист; один из самых авторитетных литературных деятелей первой трети XIX века."
}