POST http://localhost/api/authors HTTP/1.1
Content-Type: application/json


[
    {
        "surname": "Вербер",
        "name": "Бернар",
        "patronymic": "-",
        "biography": "французский философ и писатель, работающий в жанрах мистицизма, фантастики и детектива. Бернар Вербер родился 18 сентября 1961 года в Тулузе в еврейской семье."
    },
    {
        "surname": "Пушкин",
        "name": "Александр",
        "patronymic": "Сергеевич",
        "biography": "Русский поэт, драматург и прозаик, заложивший основы русского реалистического направления, литературный критик и теоретик литературы, историк, публицист, журналист; один из самых авторитетных литературных деятелей первой трети XIX века."
    }
]

##########################################################
POST http://localhost/api/books HTTP/1.1
Content-Type: application/json

[
    {
        "name": "Пиковая дама",
        "genre": "Ужасы",
        "description": "Повесть с мистическими элементами, послужившая источником сюжета одноимённой оперы П. И. Чайковского. В жанровом отношении повесть примыкает к таким (неоконченным) замыслам Пушкина, как «Египетские ночи».",
        "author": 3
    },
    {
        "name": "Метель",
        "genre": "Повесть",
        "description": "Повесть из цикла «Повестей покойного Ивана Петровича Белкина», написанная в 1830 в Болдине и изданная в 1831 году. Повесть написана последней в цикле; она была закончена 20 октября 1830 года. Экранизирована в 1964 году.",
        "author": 3
    }
]

##########################################################
POST http://localhost/api/comments HTTP/1.1
Content-Type: application/json